title: <p align="center"> Chirag Nahar </p>
logo: /assets/img/WhatsApp Image 2020-05-16 at 6.51.47 PM.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
